version: "3.8"

services:
  company-db:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: company_db
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - ~/containers/postgres:/var/lib/postgresql/data
    networks:
      - ecf-project-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - ecf-project-network

networks:
  ecf-project-network:
    driver: bridge
